### ISSUE TITLE
log4j 2 status for TLS-Attacker

### ISSUE THREAD

**Issue by roycewilliams** [tls-attacker/TLS-Attacker#121]
Checking on log4j 2 status for this project.

**Comment by ic0ns** [comment]
Its fixed in the current master branch. Older versions were vulnerable but the risk is pretty low, given that you usually scan your own systems and its usually not a service running somewhere on the internet. I couldn't deploy it to maven central yet since the servers are overloaded, probably next week.

**Comment by roycewilliams** [comment]
Best I could ask for - thanks very much!
