### ISSUE TITLE
Don't silently ignore unknown XML elements

### ISSUE THREAD

**Issue by sandwm** [tls-attacker/TLS-Attacker#73]
When passing a `-workflow_input` XML file to TLS-Client.jar and the XML contains unknown tags or unexpected text content, those are silently ignored, as long as it's at least valid XML. Please include at least a warning in the TLS-Client output (as well as TLS-Server and possibly others) when encountered XML elements are ignored.

Some examples (used with `java -jar TLS-Client.jar -connect example.org:8420 -workflow_input ~/workflow_start.xml`):

```
    <Send>
        <messages>
            <Application>
                <Data>
                    416c69636520616e6420426f62
                </Data>
            </Application>
        </messages>
    </Send>
```

The element `<Data>` is silently ignored.

```
    <Send>
        <messages>
            <Application>
                <data>
                    416c69636520616e6420426f62
                </data>
            </Application>
        </messages>
    </Send>
```

`<data>` is a known tag, but the text content is ignored.

```
    <Send>
        <messages>
            <Application>
                <data>
                    <byteArrayExplicitValueModification>
                        <explicitValue>
                            416c69636520616e6420426f62
                        </explicitValue>
                    </byteArrayExplicitValueModification>
                </data>
            </Application>
        </messages>
    </Send>
```

This works (sending an ApplicationMessage with data "Alice and Bob"). However this working version can't be distinguished from the wrong versions above just from the regular TLS-Client output. It is possible to detect the error using `-debug` or `-workflow_output`, but that requires you to already have guessed there might be an error in your XML (and ideally the location where it might be located, so you don't have to read and check the full, very long debug output).

Warning the user about the ignored elements would help very much if you e.g. picked the wrong tag name (missing an easily accessible list of all possible tags and their valid children), missed some intermediate tags (compare examples 2 and 3) or simply have a typo in a tag name.

**Comment by ic0ns** [comment]
The first case, where Data is "unknown" we can definitely do something about and warn the user. I am not sure how to do this with jaxb yet, but I am sure there is a way.

For the other cases the problem is more tricky. The problem is that TLS-Attacker allows users to reuse executed WorkflowTrace. An executed Traces contains the raw values inside the fields. When the WorkflowTrace is loaded it immediately removes all those static values. If we would warn the user about this we would probably create a lot of logger noise if the WorkflowTrace was simply adapted from an already executed trace. I am unsure if this is just a problem with our design in general or if there is something we can do about it. Imho there is no real solution as WorkflowTraces are used as an Input and Output format at the same time.

**Comment by sandwm** [comment]
Yeah, I see the problem with reused WorkflowTraces. If I understand it correctly, the static values are only discarded if not part of some (Modifiable Variable) element which expects those values? Maybe it would be possible to issue a message like this just for the first static value which is discarded?

> Discarding unused static values. First occurrence at line 42. (This is expected if reusing a -workflow_output file as a -workflow_input.)

That way you wouldn't get spammed when reusing WorkflowTraces, but still get a warning if your hand crafted input contains ignored values.

**Comment by ic0ns** [comment]
Yes, I think that is a good idea. We can do that.

**Comment by ic0ns** [comment]
TLS-Attacker now warns the user if OriginalValues are still present in a loaded WorkflowTrace, starting with TLS-Attacker 3.8.0
